# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            La vie... Société... Mereo
tagline:          La vie selon Mereo
description:      Point de vue sociologique de la société
url:              http://mereo.ca
baseurl:          

author:
  name:           'Mereo'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# The code that will permit us to have just a preview of the post
excerpt_separator: <!--more-->

gems:   
- jekyll-paginate
- jekyll-sitemap
